version: 2

builds:
  - id: rosetta
    main: ./cmd/rosetta
    binary: rosetta
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    flags: [-trimpath]
    ldflags: [-s -w]
  - id: rosetta-server
    main: ./cmd/rosetta-server
    binary: rosetta-server
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    flags: [-trimpath]
    ldflags: [-s -w]

archives:
  - ids: [rosetta, rosetta-server]
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

sboms:
  - artifacts: archive

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
