package rosetta

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGoldenArtifactsSatisfyTargetContracts(t *testing.T) {
	tests := []struct {
		target string
		file   string
	}{
		{TargetOpenShell, "openshell.yaml"},
		{TargetOpenCode, "opencode.json"},
		{TargetCodex, "codex.toml"},
		{TargetClaude, "claude-code.json"},
	}
	for _, tt := range tests {
		t.Run(tt.target, func(t *testing.T) {
			body, err := os.ReadFile(filepath.Join("testdata", "golden", tt.file))
			if err != nil {
				t.Fatal(err)
			}
			if err := validateArtifactContract(Artifact{Target: tt.target, Content: string(body)}); err != nil {
				t.Fatal(err)
			}
		})
	}
}

func TestTargetContractsRejectBroadenedArtifacts(t *testing.T) {
	tests := []struct {
		name     string
		artifact Artifact
	}{
		{"OpenShell audit endpoint", Artifact{Target: TargetOpenShell, Content: strings.ReplaceAll(readGolden(t, "openshell.yaml"), "enforcement: enforce", "enforcement: audit")}},
		{"OpenCode permissive default", Artifact{Target: TargetOpenCode, Content: strings.Replace(readGolden(t, "opencode.json"), `"*": "deny"`, `"*": "allow"`, 1)}},
		{"Codex inherited profile", Artifact{Target: TargetCodex, Content: strings.Replace(readGolden(t, "codex.toml"), `description = "Generated by Rosetta from Cedar-authorized capabilities."`, `extends = ":read-only"`, 1)}},
		{"Claude bypass mode", Artifact{Target: TargetClaude, Content: strings.Replace(readGolden(t, "claude-code.json"), `"dontAsk"`, `"bypassPermissions"`, 1)}},
		{"Claude network grant", Artifact{Target: TargetClaude, Content: strings.Replace(readGolden(t, "claude-code.json"), `"allowedDomains": []`, `"allowedDomains": ["api.example.com"]`, 1)}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if err := validateArtifactContract(tt.artifact); err == nil {
				t.Fatal("expected broadened artifact to be rejected")
			}
		})
	}
}

func readGolden(t *testing.T, name string) string {
	t.Helper()
	body, err := os.ReadFile(filepath.Join("testdata", "golden", name))
	if err != nil {
		t.Fatal(err)
	}
	return string(body)
}
